In [ ]:
n = 2000
x1 = rnorm(n, 15, 1)
x2 = rnorm(n, 5, 2)
x3 = rnorm(n, 2, 0.5)
x4 = rnorm(n, 25, 5)
e = rnorm(n)
y = 50 + 0*x1 + 5*x2 + 0*x3 + 0*x4 + e

base = data.frame(x1,x2,x3,x4,y)
View(base)

     x1       x2       x3        x4        y
1    13.91972 9.199154 0.9077051 25.127078 96.22570
2    14.77974 6.230099 2.3509381  9.777443 80.41319
3    15.02092 8.827297 2.1292375 20.367846 94.93858
4    14.99972 2.805893 2.4001553 24.629704 64.56943
5    15.05157 2.713145 0.2552515 31.959376 63.34879
6    15.02012 7.990316 2.2225489 22.762835 88.49724
7    17.94336 3.888429 1.6948869 26.642932 68.52901
8    14.94839 1.982620 2.4767918 23.099308 57.04547
9    15.71019 3.255679 2.2980484 21.569343 66.59638
10   16.03342 4.659668 2.1659086 22.225976 72.48640
11   15.02429 5.392977 2.0515565 25.883418 76.22707
12   13.78454 4.031726 2.0315625 16.383989 69.34084
13   14.60623 5.156385 1.1869481 27.851796 75.36535
14   15.48870 5.198951 3.0503635 31.109326 75.60011
15   12.98683 6.674124 2.2779452 25.572858 83.32113
16   14.80419 6.076333 1.3254288 26.413828 81.30007
17   15.39875 4.783177 2.0159166 18.271277 75.02870
18   14.97714 0.836132 1.5945151 17.401855 54.47923
19   14.23942 5.116240 1.8613475 27.977547 74.28134
20   14.34346 7.022760 2.1238080 28.205322 84.58950
21   14.74312 2.522122 1.9918994 18.257958 61.24242
22   16.28618 2.218041 2.2152902 28.984269 62.83021
23   15.96921 5.594813 1.8211670 23.135253 76.22115
24   13.55056 3.102384 1.8679285 20.827534 66.21390
25   15.16934 7.219739 1.0333419 29.897186 85.91903
26   14.91212 4.801612 1.8517988 27.767230 74.42675
27   15.62378 5.718779 1.9253383 35.743935 77.11777
28   15.45925 5.349802 2.0219632 29.023089 76.86171
29   14.88188 4.892141 1.2553982 23.989298 73.28898
30   14.70335 3.383916 2.0934672 26.645518 69.13866
⋮    ⋮        ⋮        ⋮         ⋮         ⋮
1971 17.02535 4.569953 1.773340  24.02678  73.62678
1972 17.83667 6.057007 1.859869  24.06811  79.68722
1973 16.09982 9.699489 1.236324  31.95407  99.22642
1974 14.19117 5.311594 1.411996  30.18261  75.41159
1975 14.30620 4.026609 2.186292  19.24864  70.64324
1976 13.79440 3.026453 3.170979  20.89643  63.71467
1977 13.82208 6.160196 2.718902  28.18562  81.13222
1978 13.92017 3.050210 1.839422  21.16663  63.83499
1979 14.63041 8.019242 2.235861  28.07174  91.72933
1980 15.83501 8.752455 2.102876  28.14262  94.98145
1981 14.86580 6.550305 2.093584  16.10338  84.92830
1982 14.81022 6.037239 1.320882  27.90960  80.72519
1983 14.27813 6.863096 1.655429  33.33872  82.91971
1984 15.06875 1.732623 1.154440  27.31984  60.04034
1985 14.68580 7.034308 2.046090  32.78795  84.95307
1986 14.38939 6.319456 2.792436  31.95828  81.73531
1987 14.08829 5.958586 2.831088  29.05526  82.08500
1988 13.43566 1.339306 1.854490  17.10032  55.39759
1989 16.68463 4.613900 1.259659  30.95317  74.18614
1990 13.99691 6.141093 1.048637  36.78156  81.66243
1991 15.82853 8.323660 1.847461  28.29730  90.39188
1992 16.06929 8.640472 2.103196  21.37328  94.01442
1993 14.56307 5.121681 2.456765  31.55816  74.45236
1994 12.96110 6.566717 2.471094  27.96376  84.39114
1995 14.43957 2.957672 2.526468  30.13014  65.06768
1996 16.27541 1.315356 1.868223  15.11309  56.12889
1997 13.76063 4.906347 1.762314  21.57690  74.40900
1998 15.85534 2.870887 3.216035  20.34118  61.19946
1999 13.92814 6.103042 1.760628  21.25633  80.96076
2000 14.97299 7.320253 1.767933  25.25659  87.19605

In [ ]:
vec_unos = function(n) matrix(1, nrow = n, ncol = 1)

In [ ]:
Y = matrix(base[,'y'], ncol = 1)
X = cbind(vec_unos(n),base[,c('x1','x2','x3','x4')])
X = as.matrix(X)

In [ ]:
Prueba_significancia_global = function(Y, X, alpha){

  p = ncol(X)-1
  n = nrow(Y)

  SCT = t(Y) %*% (diag(n) - (1/n)*matrix(1, nrow = n, ncol = n)) %*% Y
  SCR = t(Y) %*% (diag(n) - X%*% solve(t(X) %*%X ) %*% t(X)) %*% Y
  SCE = SCT - SCR

  CME = SCE/p
  CMR = SCR/(n-p-1)

  Fc = CME/CMR
  F_tabla = qf(1-alpha, p, n-p-1)

  tabla_anva = matrix(NA, nrow = 3, ncol = 5)
  tabla_anva = as.data.frame(tabla_anva)
  names(tabla_anva) = c('Fuente', 'GL', 'SC', 'CM', 'Fc')
  tabla_anva[,'Fuente'] = c('Regresión', 'Residual', 'Total')
  tabla_anva[,'GL'] = c(p, n-p-1, n-1)
  tabla_anva[,'SC'] = c(SCE, SCR, SCT)
  tabla_anva[,'CM'] = c(CME, CMR, NA)
  tabla_anva[,'Fc'] = c(Fc, NA, NA)

  if(Fc <= F_tabla){
    decision = paste('No se rechaza H0 al ', alpha, ' de significancia')
  }else{
    decision = paste('Se rechaza H0 al ', alpha, ' de significancia')
  }

  lista_resultados = list('Tabla ANVA de Significancia Global' = tabla_anva, "Decisión de la hipótesis" = decision)
  return(lista_resultados)

}

In [ ]:
alpha = 0.10
Prueba_significancia_global(Y, X, alpha)

$`Tabla ANVA de Significancia Global`
     Fuente   GL         SC           CM       Fc
1 Regresión    4 198151.408 49537.851969 48997.08
2  Residual 1995   2017.018     1.011037       NA
3     Total 1999 200168.426           NA       NA

$`Decisión de la hipótesis`
[1] "Se rechaza H0 al  0.1  de significancia"

In [ ]:
### -----------------------------------------------------------------------------------------

In [ ]:
  SCT = function(X, Y){
      n = nrow(Y)
      t(Y) %*% (diag(n) - (1/n)*matrix(1, nrow = n, ncol = n)) %*% Y
  }
  SCR = function(Y){
      n = nrow(Y)
      t(Y) %*% (diag(n) - X%*% solve(t(X) %*%X ) %*% t(X)) %*% Y
  }
  SCE = function(Y){
      SCT - SCR
  }

In [ ]:
hxfuncion = function(X){ return X%*% solve(t(X) %*%X ) %*% t(X)}

ERROR: Error in parse(text = x, srcfile = src): <text>:1:33: unexpected symbol
1: hxfuncion = function(X){ return X
                                    ^

In [ ]:
X = matrix(c(1, 2, 3, 4, 5, 4, 4, 4, 4, 5, 2, 2, 2, 2, 2), nrow = 5, ncol = 3)
Y = X%*% solve(t(X) %*%X ) %*% t(X)
Y

     [,1]          [,2]          [,3]          [,4]          [,5]
[1,]  7.000000e-01  4.000000e-01  1.000000e-01 -2.000000e-01  1.554312e-15
[2,]  4.000000e-01  3.000000e-01  2.000000e-01  1.000000e-01 -6.661338e-16
[3,]  1.000000e-01  2.000000e-01  3.000000e-01  4.000000e-01  2.442491e-15
[4,] -2.000000e-01  1.000000e-01  4.000000e-01  7.000000e-01 -3.552714e-15
[5,] -7.105427e-15 -7.105427e-15 -7.993606e-15 -7.993606e-15  1.000000e+00

In [ ]:
X = matrix(c( 4, 4, 4, 4, 5, 2, 2, 2, 2, 2, 1, 2, 3, 4, 5), nrow = 5, ncol = 3)
Y = X%*% solve(t(X) %*%X ) %*% t(X)
Y

     [,1] [,2]         [,3]         [,4]          [,5]
[1,]  0.7 4.000000e-01 1.000000e-01 -2.000000e-01 2.220446e-16
[2,]  0.4 3.000000e-01 2.000000e-01  1.000000e-01 3.330669e-16
[3,]  0.1 2.000000e-01 3.000000e-01  4.000000e-01 4.440892e-16
[4,] -0.2 1.000000e-01 4.000000e-01  7.000000e-01 1.110223e-15
[5,]  0.0 8.881784e-16 1.776357e-15  2.664535e-15 1.000000e+00

In [ ]:
hxfuncion(matrix(c(1, 2, 3, 4, 5, 6), nrow = 2, ncol = 3))

ERROR: Error in solve.default(t(X) %*% X): Lapack routine dgesv: system is exactly singular: U[3,3] = 0

In [ ]:
diag(3)

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

In [ ]:
?solve

In [ ]:
(matrix(c(1, 2, 3, 4, 4, 4, 4, 4, 2, 2, 2, 2), nrow = 4, ncol = 3))

     [,1] [,2] [,3]
[1,] 1    4    2
[2,] 2    4    2
[3,] 3    4    2
[4,] 4    4    2

In [ ]:
solve(matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2))

     [,1] [,2]
[1,] -2    1.5
[2,]  1   -0.5

In [ ]:
matrix(c(1, 2, 3, 4), nrow = 2, ncol = 2)

     [,1] [,2]
[1,] 1    3
[2,] 2    4

##SUBGRUPO DE **VARIABLES**

In [ ]:
#======================================================================#
#      Practica Calificada N°3 Modelos Lineales                        #
#                                                                      #
#      Lin Chiu Chen Yang - 20200403F                                  #
#                                                                      #
# Prueba de significancia para un subgrupo de variables del modelo     #
#                                                                      #
#======================================================================#

# ==== Construimos la funcion ==========================================
#
#    argumentos:
#
#       X : Matriz X donde las columnas son {x1, x2, ..., xp}
#       Y : Vector Y
#        alpha : por defecto(0.05)
#   va_interes : vector de las xi de interes si es xi, xj entonces
#                va_interes=c(i, j).
#
#=======================================================================

prueba_significancia_subgrupo <- function(X, Y, alpha=0.05, va_interes) {

  p = ncol(X)-1
  n = nrow(Y)
  k = length(va_interes)

  X1 <- X[, -(va_interes+1)]
  Hx = X %*% solve(t(X) %*% X ) %*% t(X)
  Hx1 = X1 %*% solve(t(X1) %*% X1 ) %*% t(X1)

  SCEB1 = t(Y) %*% Hx1 %*% Y
  SCEB2B1 = t(Y) %*% (Hx - Hx1) %*% Y
  SCR = t(Y) %*% (diag(n) - Hx) %*% Y
  SCT = t(Y) %*% Y

  CMEB1 = SCEB1/(p+1-k)
  CMEB2B1 = SCEB2B1/(k)
  CMR = SCR/(n-p-1)

  Fc = CMEB2B1/CMR
  F_tabla = qf(1-alpha, k, n-p-1)

  print("ANVA")

  tabla_anva = matrix(NA, nrow = 4, ncol = 5)
  tabla_anva = as.data.frame(tabla_anva)
  names(tabla_anva) = c('Fuente', 'GL', 'SC', 'CM', 'Fc')
  tabla_anva[,'Fuente'] = c('β1', 'β2|β2', 'residual', 'Total')
  tabla_anva[,'GL'] = c(p+1-k, k, n-p-1, n)
  tabla_anva[,'SC'] = c(SCEB1, SCEB2B1, SCR, SCT)
  tabla_anva[,'CM'] = c(CMEB1, CMEB2B1, CMR, NA)
  tabla_anva[,'Fc'] = c(NA, Fc, NA,  NA)
  View(tabla_anva)


  print(paste("el F calculado vale:", Fc))
  print(paste("el F tabla vale:", F_tabla))
  if(Fc <= F_tabla){
    sprintf('No se rechaza H0 al %s de significancia', alpha)
  }else{
    sprintf('Se rechaza H0 al %s de significancia', alpha)
  }

}

In [ ]:
# Simulamos Datos =======================================

n = 2000
x1 = rnorm(n, 15, 1)
x2 = rnorm(n, 5, 2)
x3 = rnorm(n, 2, 0.5)
x4 = rnorm(n, 25, 5)
e = rnorm(n)
y = 50 + 0*x1 + 1*x2 + 0*x3 + 26*x4 + e

base = data.frame(x1,x2,x3,x4,y)

vec_unos = function(n) matrix(1, nrow = n, ncol = 1)

Y = matrix(base[,'y'], ncol = 1)
X = cbind(vec_unos(n),base[,c('x1','x2','x3','x4')])
X = as.matrix(X)


# Probamos la funcion =======================================

prueba_significancia_subgrupo(X, Y,alpha = 0.01, va_interes=c(2, 3))

  Fuente   GL   SC           CM           Fc
1 β1          3 1.048942e+09 3.496475e+08       NA
2 β2|β2       2 7.917645e+03 3.958822e+03 3938.089
3 residual 1995 2.005503e+03 1.005265e+00       NA
4 Total    2000 1.048952e+09           NA       NA

[1] "ANVA"
[1] "el F calculado vale: 3938.08926985561"
[1] "el F tabla vale: 4.61581693616031"

[1] "Se rechaza H0 al 0.01 de significancia"